services:
  postgres:
    image: postgres:14.3
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5    
    environment:
      POSTGRES_PASSWORD: swallow99
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb.d/01-create_db.sh:/docker-entrypoint-initdb.d/01-create_db.sh
  init-estuary:
    build: .
    command: init
    volumes:
      - estuary-data:/data
    depends_on:
      postgres:
        condition: service_healthy
  estuary:
    build: .
    command: estuary
    volumes:
      - estuary-data:/data
    depends_on:
      init-estuary:
        condition: service_completed_successfully

volumes:
  estuary-data:
  db-data:

